openapi: 3.0.4
info:
  title: Cities Lookup
  description: >-
    Cities Lookup is a simple tool for looking up city data. It returns the city
    name, population, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/citieslookup:
    get:
      summary: Lookup City
      description: Lookup city data based on the city name
      operationId: citieslookup
      parameters:
        - name: city
          in: query
          schema:
            type: string
          required: true
          description: The city name for which you want to get the data (e.g., New York)
          example: San Francisco
        - name: limit
          in: query
          schema:
            type: integer
          required: false
          description: Limit number of cities that match your search criteria
          example: 5
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  search: San Francisco
                  foundCities:
                    - name: San Francisco de Laish√≠
                      altName: ''
                      country: AR
                      featureCode: PPLA2
                      population: 4384
                      loc:
                        type: Point
                        coordinates:
                          - -58.63039
                          - -26.24262
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
